"""Enable Outbound Network Activities

Revision ID: 6dfba265232e
Revises: 9c0795f22577
Create Date: 2020-07-16 09:41:58.110396+00:00

"""
from alembic import op
import json
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dfba265232e'
down_revision = '9c0795f22577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_advanced', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adv_network_activity', sa.TEXT(), nullable=True))

    op.execute("UPDATE system_advanced SET adv_network_activity = '{\"type\": \"DENY\", \"activities\": []}'")

    with op.batch_alter_table('system_advanced', schema=None) as batch_op:
        batch_op.alter_column('adv_network_activity',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_advanced', schema=None) as batch_op:
        batch_op.drop_column('adv_network_activity')

    # ### end Alembic commands ###
